application: studychumapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /
  script: index.php

- url: /landingpage
  script: landing.php

- url: /create
  script: create.php

- url: /signup
  script: signup.php

- url: /profile
  script: profile.php

- url: /database
  script: models/database.php

- url: /learner
  script: learner.php