application: studychumapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /
  script: index.php

- url: /landingpage
  script: landing.php

- url: /create
  script: create.php

- url: /profile
  script: profile.php

- url: /chums
  script: chums.php

- url: /user
  script: user.php

- url: /activity
  script: activity.php

- url: /success
  script: success.php

- url: /mychums
  script: userchums.php

- url: /forum
  script: forum.php

- url: /create_discussion
  script: create_discussion.php

- url: /discussions
  script: discussions.php

- url: /chat
  script: chat.php


